// data.js
// Songs array — add all 600 entries gradually in this format.
const songs = [
  {
    id: 1,
    title: "దేవుని స్తుతియించుడి",
    altTitle: "Devuni Sthuthiyinchudi", // optional English/Transliteration title
    lyrics: [
      "పల్లవి: దేవుని స్తుతియించుడి - ఎల్లప్పుడు",
      "       దేవుని స్తుతియించుడి  ...ఆ… ఆ…",
      "",

      "1. ఆయన పరిశుద్ధ - ఆలయమందు ",
      "   ఆయన సన్నిధిలో ఆ… ఆ…                      ||దేవుని||",
      "",
      "2. ఆయన బలమును - ప్రసిద్ధి చేయు ",
      "   ఆకశవిశాలమందు ఆ… ఆ…                       ||దేవుని||",
      "",
      "3. ఆయన పరాక్రమ - కార్యములన్ బట్టి ",
      "   ఆయన ప్రభావమును ఆ… ఆ…                    ||దేవుని||",
      "",
      "4. బూరధ్వనితో - ఆయనన్ స్తుతించుడి ",
      "   స్వరమండలములతో ఆ… ఆ…                    ||దేవుని||",
      "",
      "5. సన్నతంతుల - సితారతోను ",
      "   చక్కని స్వరములతో ఆ… ఆ…                     ||దేవుని||",
      "",
      "6. తంబురతోను - నాట్యముతోను ",
      "   తంతి వాద్యములతో ఆ… ఆ…                     ||దేవుని||",
      "",
      "7. పిల్లన గ్రోవుల - చల్లగనూది ",
      "   ఎల్ల ప్రజలు జేరి ఆ… ఆ…                        ||దేవుని||",
      "",
      "8. మ్రోగు తాళములతో - ఆయనన్ స్తుతించుడి ",
      "   గంభీర తాళముతో ఆ… ఆ…                        ||దేవుని||",
      "",
      "9. సకల ప్రాణులు - యెహోవన్ స్తుతించుడి ",
      "   హల్లెలూయా ఆమెన్ ఆ… ఆ… ",
      "   హల్లెలూయా ఆమెన్ - ఎల్లప్పుడు                  ||దేవుని||"
    ],
    englishLyrics: [
  "Pallavi: Devuni Sthuthiyinchudi - Ellappudu",
  "       Devuni Sthuthiyinchudi  ...Aa… Aa…",
  "",

  "1. Aayana Parishuddha - Aalayamandu ",
  "   Aayana Sannidhilo Aa… Aa…                      ||Devuni||",
  "",
  "2. Aayana Balamunu - Prasiddhi Cheyu ",
  "   Aakashavishaalamandu Aa… Aa…                   ||Devuni||",
  "",
  "3. Aayana Paraakrama - Kaaryamulan Batti ",
  "   Aayana Prabhavamunu Aa… Aa…                    ||Devuni||",
  "",
  "4. Booradhvanitho - Aayanan Sthuthinchudi ",
  "   Svaramandalamulatho Aa… Aa…                    ||Devuni||",
  "",
  "5. Sanna Thanthula - Sithaarathonu ",
  "   Chakkani Svaramulatho Aa… Aa…                  ||Devuni||",
  "",
  "6. Thamburathonu - Naatyamuthonu ",
  "   Thanthi Vaadyamuthonu Aa… Aa…                  ||Devuni||",
  "",
  "7. Pillana Grovula - Challaganoodi ",
  "   Ellaprajalu Jeri Aa… Aa…                       ||Devuni||",
  "",
  "8. Mrogu Thaalamulatho - Aayanan Sthuthinchudi ",
  "   Gambheera Thaalamutho Aa… Aa…                  ||Devuni||",
  "",
  "9. Sakala Praanulu - Yehovan Sthuthinchudi ",
  "   Hallelooyaa Aamen Aa… Aa… ",
  "   Hallelooyaa Aamen - Ellappudu                  ||Devuni||"
]


  },
  // Add this after the first song in the songs array
{
  id: 2,
  title: "ఆయన మందిర - ఆవరణములో",
  altTitle: "Aayana Mandira - Aavaranamulo",
  lyrics: [
    "పల్లవి: ఆయన మందిర - ఆవరణములో = యెహోవ దేవుని - స్తుతించుడి",
    "       భూమి-ఆకాశమందున = మీరెల్లరుకూడి- స్తుతించుడి       ॥ఆయన॥",
    "",
    "అ.ప: రాజా ఓ రాజా-ఓ రాజులకు = రాజైనంచు- స్తుతించుడి      ॥ఆయన॥",
    "",
    "1. సర్వాధికారుడంచు - సర్వశక్తిమంతుడంచు ",
    "   సంపూర్ణ ప్రేమరూపి-సాధుల శ్రీమంతుడంచు",
    "   సృష్టి నిన్ స్మరణ చేసెనో - ఓ............... స్తుతించుడి    ॥ఆయన॥",
    "",
    "2. పెళ పెళ మ్రోగెడి- ఉరుములలోన- రాజా .... ఓ రాజా",
    "   తళ తళ మెరిసెడీ-మెరుపులలోన రాజా .. ఓ రాజా",
    "   చలనము కలిగిన -జీవులలోన రాజా... ఓ రాజా",
    "   రాజాధిరాజుల-రాజా- ఓ....... ఓ...... స్తుతించుడి          ॥ఆయన॥"
  ],
  englishLyrics: [
  "Pallavi: Aayana Mandira - Aavaranamulo = Yehova Devuni - Sthuthinchudi",
  "         Bhumi-Aakaashamanduna = MeerellaruKoodi- Sthuthinchudi ॥Aayana॥",
  "",
  "A.P: Raja O Raja-O Rajulaku = Rajainchu- Sthuthinchudi      ॥Aayana॥",
  "",
  "1. Sarvaadhikaarudanchu - Sarvashaktimanthudanchu ",
  "   Sampoorna Prema Roopi-Saadula Shreemantudanchu",
  "   Srushti Nin Smarana Cheseno - O.........Sthuthinchudi    ॥Aayana॥",
  "",
  "2. Pela Pela Mrogedi- Urumulalona- Raja .... O Raja",
  "   Tala Tala Merisedi-Merupulalona Raja .. O Raja",
  "   Chalanamu Kaligina -Jeevulalona Raja... O Raja",
  "   Raajadhiraajula-Raja- O....... O...... Sthuthinchudi     ॥Aayana॥"
]

},

{
  id: 3,
  title: "ఆ-ఆ-ఆ సదా స్తుతింతు",
  altTitle: "Aa-Aa-Aa Sadaa Sthuthintu",
  lyrics: [
    "పల్లవి : ఆ-ఆ-ఆ సదా స్తుతింతు. యేసు రక్షకా - యేసు రక్షకా ",
    "        నిన్నే స్తుతింతు రక్షకా నిన్నే స్తుతింతు రక్షకా          ॥ఆ॥",
    "",
    "1. కష్టాలయందు స్తుతింతు- నష్టాలయందు స్తుతింతు ",
    "   నిష్ట అదేకదా - స్పష్టమదేకదా- శ్రేష్టమదేకదా                 ॥ఆ॥",
    "",
    "2. నిందలయందు స్తుతింతు - అపనిందలయందు స్తుతింతు",
    "   ఆనందమని - పై విందుగని నీ యందుమని                ॥ఆ॥",
    "",
    "3. ప్రాణాపాయములో స్తుతింతు - నీ ప్రాణాపాయము దలంతు", 
    "   బహు ప్రాణమిదే - నాకు ధ్యానమిదే - లోక త్రాణమిదే       ॥ఆ॥",
    "",
    "4. కరువు దుఃఖములో స్తుతింతు- యిరుకు వ్యాధులలో స్తుతింతు",
    "   నా నిరకునదే - భక్త సరుకునదే - క్రీస్తుకొరకు పదే          ॥ఆ॥",
    "",
    "5. అనుమానమున్న స్తుతింతు - అవమానమున్న స్తుతింతు",
    "   నసుచంపుకొని - వినుకొందునని - కనుమూసుకొని           ॥ఆ॥",
    "",
    "6. ఉపకారములకై స్తుతింతు - అపకారములకు స్తుతింతు",
    "   అపవాదు కాని - అపవాదు రాని కృప అదే అని             ॥ఆ॥"
  ],
  englishLyrics: [
  "Pallavi: Aa-Aa-Aa Sadaa Sthuthintu. Yesu Rakshaka - Yesu Rakshaka ",
  "        Ninne Sthuthintu Rakshaka Ninne Sthuthintu Rakshaka    ॥Aa॥",
  "",
  "1. Kashtaalayandu Sthuthintu- Nashtaalayandu Sthuthintu ",
  "   Nishtha Adekada - Spashtam Adekada- Shreshtam Adekada  ॥Aa॥",
  "",
  "2. Nindalayandu Sthuthintu - Apanindalayandu Sthuthintu",
  "   Anandamani - Pai Vindugani Nee Yandumani                ॥Aa॥",
  "",
  "3. Praanaapaayamulo Sthuthintu - Nee Praanaapaayamu Dalantu", 
  "   Bahu Praanamide - Naaku Dhyanamide - Loka Traanamide     ॥Aa॥",
  "",
  "4. Karuvu Duhkhamulo Sthuthintu- Yeruku Vyadhulalo Sthuthintu",
  "   Naa Nirakunade - Bhakta Sarakunade - Kreestukoraku Pade   ॥Aa॥",
  "",
  "5. Anumaanamunna Sthuthintu - Avamaanamunna Sthuthintu",
  "   Nasuchampukoni - Vinukondunani - Kanumoosukoni           ॥Aa॥",
  "",
  "6. Upakaaramulakai Sthuthintu - Apakaaramulaku Sthuthintu",
  "   Apavaadu Kaani - Apavaadu Raani Krupa Ade Ani             ॥Aa॥"
]
},
{
  id: 4,
  title: "జీవంబు నిచ్చిన దేవుడా",
  altTitle: "Jeevambu Nicchina Devuda",
  lyrics: [
    "పల్లవి: జీవంబు నిచ్చిన - దేవుడా = నేపాడేన నీకు - నిరంతరము.",
    "        హల్లెలూయా - హల్లెలూయా = పావనుడా నీకు - పలుమారునే",
    "        నింకేమియియ్యంగ - పాత్రుండను = హల్లెలూయా - హల్లెలూయా",
    "",
    "1. వెలుగిచ్చినావు - వెలిగించినావు = గాలిని మాకై - కలుగజేసి",
    "   అనుదినము మాకు - ఆహారమిచ్చి = ఊపిరివోసి కాపాడితివి ",
    "   ఎంచలేక నీ - మంచిపనులు = హల్లెలూయ - హల్లెలూయ - అని పాడెడ",
    "   హల్లెలూయ - హల్లేలూయ అని పాదెన",
    "   హితుడా నీకే- యీస్తుతిగీతము = హల్లెలూయ - హల్లెలూయ     ॥జీవం॥",
    "",
    "2. కరుణ కిరీట- మిచ్చావని = గడిగడికి నాతో - నడినావని",
    "   కోపించువాడు - కాడంచు నా = పాపంబులెల్ల -పాటించడు      ॥ఎంచ॥"
  ],
  englishLyrics: [
  "Pallavi: Jeevambu Nicchina - Devuda = Nepaadena Neeku - Nirantaramu.",
  "        Halleluyaa - Halleluyaa = Paavanudaa Neeku - Palumaarune",
  "        Ninkemi Iyyanga - Paathrundanu = Halleluyaa - Halleluyaa",
  "",
  "1. Velugicchinaavu - Veliginchinaavu = Gaalini Maakai - Kalugajeshi",
  "   Anudinamu Maaku - Aahaaramicchi = OopiriPosi Kaapaaditivi",
  "   Enchaleka Nee - Manchipanulu = Halleluyaa - Halleluyaa - Ani Paadeda",
  "   Halleluyaa - Halleluyaa Ani Paadena",
  "   Hituda Neeke - Yeestutigeetamu = Halleluyaa - Halleluyaa ॥Jeevam॥",
  "",
  "2. Karuna Kirita- Michchaavani = Gadigadiki Naato - Nadinaavani",
  "   Kopinchuvadu-Kaadancha Naa=Paapambulalla-Paatchinchadu   ॥Encha॥"
]
},
{
  id: 5,
  title: "యెహోవాను గానము చేసెదము",
  altTitle: "Yehovanu Gaanamu Chesedamu",
  lyrics: [
    "పల్లవి: యెహోవాను గానము - చేసెదము ఏకముగా",
    "       మనకు రక్షకు డాయనే - ఆయన మహిమ పాడెదము ",
    "       ఆయనను వర్ణించెదము - ఆయనే దేవుడు మనకు",
    "",
    "1. యుద్ధశూరుడు యెహోవా - నా బలము నా గానము",
    "   నాపితరుల దేవుడు - అయన పేరు యెహోవా       ॥యెహో॥",
    "",
    "2. ఫరోరధముల సేనలను - తన శ్రేష్టాధిపతులను",
    "   ఎర్ర సముద్రములోన - ముంచి వేసెను యెహోవా   ॥యెహో॥",
    "",
    "3. నీ మహిమాతిశయమున- కోపాగ్ని రగులజేసి",
    "   చెత్తవలె దహించెదవు - నీపై లేచు వారిని          ॥యెహో॥",
    "",
    "4. దోపుడు సొమ్ము పంచుకొని - ఆశ తీర్చుకొందును",
    "   నా కత్తి దూసెదను - అని శత్రువనుకొనేను          ॥యెహో॥",
    "",
    "5. వేల్పులలో నీ సముడెవడు - పరిశుద్ధ మహనీయుడా   ॥యెహో॥",
    "   అద్భుతమైన పూజ్యుడా - నీ వంటి వాడెవడు",
    "",
    "6. ఇశ్రాయేలీయులంతా ఎంతో - సురక్షితముగా",
    "   సముద్రము మధ్యను - ఆరిన నేలను నడచిరి        ॥యెహో॥"
  ],
  englishLyrics: [
  "Pallavi: Yehovanu Gaanamu - Chesedamu Ekamuga",
  "       Manaku Rakshakudayane - Ayana Mahima Paadedamu",
  "       Ayananu Varninchedamu - Ayane Devudu Manaku",
  "",
  "1. Yuddhashoorudu Yehovaa - Naa Balam Naa Gaanamu",
  "   Naapitarula Devudu - Ayana Peru Yehovaa       ॥Yeho॥",
  "",
  "2. Pharo Rathamula Senalanu - Tana Shreshtaadhipatulanu",
  "   Erra Samudramulona - Munchi Vesenu Yehovaa   ॥Yeho॥",
  "",
  "3. Nee Mahima Atishayamuna - Kopaagni Ragulajeshi",
  "   Chettavale Dahinchedavu - Neepai Lechu Vaarini          ॥Yeho॥",
  "",
  "4. Dopudu Sommu Panchukoni - Aasha Teerchukondunu",
  "   Naa Katti Doosedanu - Ani Shatruvanukonenu          ॥Yeho॥",
  "",
  "5. Velpulalo Nee Samudyevadhu - Parishuddha Mahaneeyudaa   ॥Yeho॥",
  "   Adbhutamaina Poojyudaa - Nee Vanti Vaadevadu",
  "",
  "6. Ishrayeliyulantaa Ento - Surakshitamuga",
  "   Samudramu Madhyanu - Aarina Nelanu Nadachiri        ॥Yeho॥"
]
},
{
  id: 6,
  title: "గీతం గీతం జయ జయగీతం",
  altTitle: "Geetam Geetam Jaya Jayageetam",
  lyrics: [
    "పల్లవి : గీతం గీతం జయ జయగీతం - చేయి తట్టిపాడెదము",
    "          యేసురాజు లేచెను హల్లెలూయా - జయమార్చటించెదము",
    "",
    "1. చూడు సమాధిని మూసినరాయి- దొరలుచు పరులిడెను",
    "   అందు వేసినముద్ర కావలినిల్చును - దైవసుతుని ముందు     ॥గీ॥",
    "",
    "2. వలదు వలదు ఏడువ వలదు - పరుగిడి ప్రచురించుడి",
    "   తాను చెప్పిన విధమున తిరిగిలేచెను - వెళ్ళుడి గలిలయకు    ॥గీ॥",
    "",
    "3. అన్న కయపవారల సభయు - అదురుచు పరుగిడిరి",
    "   యిక దూత గణముల ధ్వనిని వినుచు - వణుకుచు భయపడిరి  ॥గీ॥",
    "",
    "4. గుమ్మముల్ తెరచి చక్కగ నడువుడి - జయవీరుడు రాగా",
    "   మీ మేళతాళ బూర వాయిద్యము - లెత్తి ధ్వనించుడి           ॥గీ॥"
  ],
  englishLyrics: [
  "Pallavi : Geetam Geetam Jaya Jayageetam - Cheyi Tattipaadedamu",
  "          Yesuraju Lechenu Halleluyaa - Jayamarchatinchedamu",
  "",
  "1. Choodu Samaadhini Moosina Raayi - Doraluchu Parulidenu",
  "   Andu Vesina Mudra Kaavalinilchunu - Daivasutuni Mundu     ॥Gee॥",
  "",
  "2. Valadu Valadu Eduva Valadu - Parugidi Prachurinchudi",
  "   Taanu Cheppina Vidhamuna Tirigi Lechenu - Velludi Galilayaku          ॥Gee॥",
  "",
  "3. Anna Kayapavaarala Sabhavu - Aduruchu Parugidiri",
  "   Yika Dootha Ganamula Dhvanini Vinuchu - Vanukuchu Bhayapadiri         ॥Gee॥",
  "",
  "4. Gummamul Terachi Chakkaga Naduwudi - Jayaveerudu Raagaa",
  "   Mee Melataala Boora Vaidyamu - Letti Dhvaninchudi           ॥Gee॥"
]},
{
  id: 7,
  title: "స్తుతియింతుము మా",
  altTitle: "Sthuthiyinthumu Maa",
  lyrics: [
    "పల్లవి : స్తుతియింతుము మా - క్రిత జనరక్షక స్తోత్రార్హుడనీవే",
    "          మా వెతలను బాపి -క్షితి బ్రోచితివి- గతవత్సరమంతా    ॥స్తుతి॥",
    "",
    "1. నూతనవత్సర-మిదిగో వచ్చెను-నూతనముగ బ్రతుకన్",
    "   నీ నీతిని మాకిడి-పాప హృదయమున్-పారగద్రోలు ప్రభో          ॥స్తుతి॥",
    "",
    "2. నూతనజీవము-నూతనశక్తి-నూతనముగ నిమ్మా",
    "   నీ నూతన బలముతో-నూతనసేవన్- బ్రీతితో జేయనిలన్         ॥స్తుతి॥",
    "",
    "3. కన్న జనకుడు-ఉన్నకుమారుని అన్నగ బంపించెన్",
    "   మనకున్న శ్రమల-నన్నిటినుండియు- పన్నుగ రక్షింపన్         ॥స్తుతి॥",
    "",
    "4. యెన్నియె యేడులు-ఎన్నగమనపై- నెన్నియొ వచ్చెనుగా",
    "   నిన్నెన్నడు ఎరుగక-బ్రతికే బ్రతుకు-బ్రతుకిలగాదు ప్రభో         ॥స్తుతి॥",
    "",
    "5. పాపము శాపము - బాపను మాకై - ప్రాపుగవచ్చితివి.",
    "   నీ దాపున జేరిన - వారికిడితివి- పాపవిమోచనమున్             ॥స్తుతి॥",
  ],
  englishLyrics: [
  "Pallavi : Sthuthiyinthumu Maa - Krita Janarakshaka Stotraarhudaniive",
  "          Maa Vetalanubapi - Kshiti Brochitivi - Gata Vatsaramantaa    ॥Stuti॥",
  "",
  "1. Noothana Vatsara Midigo Vacchenu - Noothanamuga Bratukan",
  "   Nee Neetini Maakidi - Paapa Hridayamun - Paaragadroolu Prabho       ॥Stuti॥",
  "",
  "2. Noothana Jeevamu - Noothana Shakti - Noothanamuga Nimmaa",
  "   Nee Noothana Balamuto - Noothana Sevan - Preetito Jeyanilan         ॥Stuti॥",
  "",
  "3. Kanna Janakudu - Unna Kumaaruni Annaga Bampinchen",
  "   Manakunna Shramala - Nannitinundiyu - Pannuga Rakshimpan            ॥Stuti॥",
  "",
  "4. Yenniye Yedulu - Ennagamanapai - Nennayo Vacchenugaa",
  "   Ninnennaḍu Erugaka - Bratikey Bratuku - Bratukilagaadu Prabho       ॥Stuti॥",
  "",
  "5. Paapamu Shaapamu - Baapanu Maakai - Praapuga Vacchitivi.",
  "   Nee Daapuna Jerina - Vaarikiditivi - Paapavimochanamun              ॥Stuti॥"
]},



  




  // Next songs here...
];
